spring:
  jpa:
    open-in-view: false
    # see https://vkuzel.com/spring-boot-jpa-hibernate-atomikos-postgresql-exception for details on these 2 configuration.
    # in summary, they are to prevent an unimportant SQLFeatureNotSupportedException at startup.
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  mvc:
    async:
      request-timeout: 35s
      # clingo's time limit must be <= this.
      # some buffer added for the remote server as well.
  jooq:
    sql-dialect: postgres
  servlet.multipart.max-file-size: 10MB

solver:
  timeout: 30

props:
  additional-allowed-origins:
    - https://sapling.netlify.com

logging:
  level:
    root: INFO
